export interface SendowlProduct {
  _id?: string;
  productId: string;    // ex: "78576638" — peut être vide si non connu
  productName: string;  // nom exact tel qu'il apparaît dans la colonne "Item Name" du CSV
  siteCode: string;     // code interne SendOwl : ZZOE, ZV, ZR, ZE, CL - FR, NL - EN, etc.
  siteName: string;     // shortName dashboard (ex: "ZZ FR", "Corse", "Normandie")
  destination: string;  // informatif (ex: "Madere", "Islande")
  createdAt?: Date;
  updatedAt?: Date;
}

// Map siteCode → shortName dashboard
export const SENDOWL_SITE_CODE_TO_SHORTNAME: Record<string, string> = {
  'ZZOE':    'ZZ EN',
  'ZV':      'ZZ FR',
  'ZR':      'ZZ R',
  'ZE':      'ZZ ES',
  'CL - EN': 'Corse',
  'CL - FR': 'Corse',
  'CL - DE': 'Corse',
  'CL - IT': 'Corse',
  'CL - ES': 'Corse',
  'CL - NL': 'Corse',
  'NL - FR': 'Normandie',
  'NL - EN': 'Normandie',
  'NL - DE': 'Normandie',
  'NL - ES': 'Normandie',
  'NL - IT': 'Normandie',
  'NL - NL': 'Normandie',
};

// Données initiales à seeder en base
export const SENDOWL_PRODUCTS_SEED: Omit<SendowlProduct, '_id' | 'createdAt' | 'updatedAt'>[] = [
  { productId: '78250166', productName: 'The road trip guide - Andalucia (eBook) (x1)',                   siteCode: 'ZZOE', siteName: 'ZZ EN',     destination: 'Andalousie' },
  { productId: '78250169', productName: 'The road trip guide - Corsica (eBook) (x1)',                     siteCode: 'CL - EN', siteName: 'Corse',  destination: 'Corse' },
  { productId: '78250170', productName: 'The road trip guide - South Corsica (eBook) (x1)',               siteCode: 'CL - EN', siteName: 'Corse',  destination: 'Corse' },
  { productId: '78250172', productName: 'The road trip guide - North Corsica (eBook) (x1)',               siteCode: 'CL - EN', siteName: 'Corse',  destination: 'Corse' },
  { productId: '78250174', productName: 'The road trip guide - Crete (eBook) (x1)',                       siteCode: 'ZZOE', siteName: 'ZZ EN',     destination: 'Crete' },
  { productId: '78250177', productName: 'The road trip guide - Iceland (eBook) (x1)',                     siteCode: 'ZZOE', siteName: 'ZZ EN',     destination: 'Islande' },
  { productId: '78250180', productName: 'The road trip guide - Iceland Ring Road (eBook) (x1)',           siteCode: 'ZZOE', siteName: 'ZZ EN',     destination: 'Islande' },
  { productId: '78250184', productName: 'The road trip guide - Iceland in Winter (eBook) (x1)',           siteCode: 'ZZOE', siteName: 'ZZ EN',     destination: 'Islande' },
  { productId: '78250186', productName: 'Explore and Photograph Lanzarote (eBook) (x1)',                  siteCode: 'ZZOE', siteName: 'ZZ EN',     destination: 'Lanzarote' },
  { productId: '78250191', productName: 'The road trip guide - New Zealand (eBook) (x1)',                 siteCode: 'ZZOE', siteName: 'ZZ EN',     destination: 'Nouvelle Zelande' },
  { productId: '78250193', productName: 'The road trip guide - NZ North Island (eBook) (x1)',             siteCode: 'ZZOE', siteName: 'ZZ EN',     destination: 'Nouvelle Zelande' },
  { productId: '78250195', productName: 'The road trip guide - NZ South Island (eBook) (x1)',             siteCode: 'ZZOE', siteName: 'ZZ EN',     destination: 'Oman' },
  { productId: '78250198', productName: 'The road trip guide - Oman (eBook) (x1)',                        siteCode: 'ZZOE', siteName: 'ZZ EN',     destination: 'Portugal' },
  { productId: '78250200', productName: 'The road trip guide - Portugal (eBook) (x1)',                    siteCode: 'ZZOE', siteName: 'ZZ EN',     destination: 'Portugal' },
  { productId: '78250202', productName: 'The road trip guide - Lisbon Sintra Algarve (eBook) (x1)',       siteCode: 'ZZOE', siteName: 'ZZ EN',     destination: 'Portugal' },
  { productId: '78250203', productName: 'Explore and Photograph Santorini (eBook) (x1)',                  siteCode: 'ZZOE', siteName: 'ZZ EN',     destination: 'Santorin' },
  { productId: '78250207', productName: 'The road trip guide - Scotland (eBook) (x1)',                    siteCode: 'ZZOE', siteName: 'ZZ EN',     destination: 'Ecosse' },
  { productId: '78250210', productName: 'The road trip guide - Edinburgh to Skye (eBook) (x1)',           siteCode: 'ZZOE', siteName: 'ZZ EN',     destination: 'Ecosse' },
  { productId: '78250215', productName: 'The road trip guide - Slovenia (eBook) (x1)',                    siteCode: 'ZZOE', siteName: 'ZZ EN',     destination: 'Slovenie' },
  { productId: '78250261', productName: 'Le guide du road trip – Andalousie (eBook) (x1)',                siteCode: 'ZV',   siteName: 'ZZ FR',     destination: 'Andalousie' },
  { productId: '78250264', productName: 'Le guide du road trip – Corse (eBook) (x1)',                     siteCode: 'CL - FR', siteName: 'Corse',  destination: 'Corse' },
  { productId: '78250266', productName: 'Le guide du road trip – Corse du Nord (eBook) (x1)',             siteCode: 'CL - FR', siteName: 'Corse',  destination: 'Corse' },
  { productId: '78250267', productName: 'Le guide du road trip – Corse du Sud (eBook) (x1)',              siteCode: 'CL - FR', siteName: 'Corse',  destination: 'Corse' },
  { productId: '78250279', productName: 'Le guide du road trip – Crete (eBook) (x1)',                     siteCode: 'ZV',   siteName: 'ZZ FR',     destination: 'Crete' },
  { productId: '78250283', productName: 'Le guide du road trip – Islande (eBook) (x1)',                   siteCode: 'ZV',   siteName: 'ZZ FR',     destination: 'Islande' },
  { productId: '78250284', productName: 'Le guide du road trip – Islande Ring Road (eBook) (x1)',         siteCode: 'ZV',   siteName: 'ZZ FR',     destination: 'Islande' },
  { productId: '78250286', productName: 'Le guide du road trip – Islande en hiver (eBook) (x1)',          siteCode: 'ZV',   siteName: 'ZZ FR',     destination: 'Islande' },
  { productId: '78250287', productName: 'Explorer et Photographier Lanzarote (eBook) (x1)',               siteCode: 'ZV',   siteName: 'ZZ FR',     destination: 'Lanzarote' },
  { productId: '78250289', productName: 'Le guide du road trip – Nouvelle Zelande (eBook) (x1)',          siteCode: 'ZV',   siteName: 'ZZ FR',     destination: 'Nouvelle Zelande' },
  { productId: '78250293', productName: 'Le guide du road trip – Oman (eBook) (x1)',                      siteCode: 'ZV',   siteName: 'ZZ FR',     destination: 'Oman' },
  { productId: '78250296', productName: 'Le guide du road trip – Portugal (eBook) (x1)',                  siteCode: 'ZV',   siteName: 'ZZ FR',     destination: 'Portugal' },
  { productId: '78250299', productName: 'Le guide du road trip – Lisbonne Sintra Algarve (eBook) (x1)',   siteCode: 'ZV',   siteName: 'ZZ FR',     destination: 'Portugal' },
  { productId: '78250301', productName: 'Le guide du road trip – Ecosse (eBook) (x1)',                    siteCode: 'ZV',   siteName: 'ZZ FR',     destination: 'Ecosse' },
  { productId: '78250302', productName: 'Le guide du road trip – Edimbourg a Skye (eBook) (x1)',          siteCode: 'ZV',   siteName: 'ZZ FR',     destination: 'Ecosse' },
  { productId: '78250303', productName: 'Le guide du road trip – Slovenie (eBook) (x1)',                  siteCode: 'ZV',   siteName: 'ZZ FR',     destination: 'Slovenie' },
  { productId: '78250307', productName: 'Explorer et Photographier Santorin (eBook) (x1)',                siteCode: 'ZV',   siteName: 'ZZ FR',     destination: 'Santorin' },
  { productId: '78250321', productName: 'Der Roadtrip Reisefuhrer – Andalusien (eBook) (x1)',             siteCode: 'ZR',   siteName: 'ZZ R',      destination: 'Andalousie' },
  { productId: '78250327', productName: 'Der Roadtrip Reisefuhrer – Korsika (eBook) (x1)',                siteCode: 'CL - DE', siteName: 'Corse',  destination: 'Corse' },
  { productId: '78250332', productName: 'Der Roadtrip Reisefuhrer – Kreta (eBook) (x1)',                  siteCode: 'ZR',   siteName: 'ZZ R',      destination: 'Crete' },
  { productId: '78250334', productName: 'Der Roadtrip Reisefuhrer – Island (eBook) (x1)',                 siteCode: 'ZR',   siteName: 'ZZ R',      destination: 'Islande' },
  { productId: '78250338', productName: 'Der Roadtrip Reisefuhrer – Island im Winter (eBook) (x1)',       siteCode: 'ZR',   siteName: 'ZZ R',      destination: 'Islande' },
  { productId: '78250344', productName: 'Der Roadtrip Reisefuhrer – Neuseeland (eBook) (x1)',             siteCode: 'ZR',   siteName: 'ZZ R',      destination: 'Normandie' },
  { productId: '78250351', productName: 'Der Roadtrip Reisefuhrer – Oman (eBook) (x1)',                   siteCode: 'ZR',   siteName: 'ZZ R',      destination: 'Oman' },
  { productId: '78250354', productName: 'Der Roadtrip Reisefuhrer – Schottland (eBook) (x1)',             siteCode: 'ZR',   siteName: 'ZZ R',      destination: 'Ecosse' },
  { productId: '78250359', productName: 'Der Roadtrip Reisefuhrer – Slowenien (eBook) (x1)',              siteCode: 'ZR',   siteName: 'ZZ R',      destination: 'Slovenie' },
  { productId: '78250364', productName: 'Erkunden und Fotografieren – Santorini (eBook) (x1)',            siteCode: 'ZR',   siteName: 'ZZ R',      destination: 'Santorin' },
  { productId: '78250371', productName: 'Erkunden und Fotografieren – Lanzarote (eBook) (x1)',            siteCode: 'ZR',   siteName: 'ZZ R',      destination: 'Lanzarote' },
  { productId: '78340460', productName: 'Le guide du road trip - Normandie (eBook) (x1)',                 siteCode: 'NL - FR', siteName: 'Normandie', destination: 'Normandie' },
  { productId: '78340466', productName: 'The road trip guide - Normandy (eBook) (x1)',                    siteCode: 'NL - EN', siteName: 'Normandie', destination: 'Normandie' },
  { productId: '78394966', productName: 'Der Roadtrip Reisefuhrer – Normandie (eBook) (x1)',              siteCode: 'NL - DE', siteName: 'Normandie', destination: 'Normandie' },
  { productId: '78439542', productName: 'Der Roadtrip Reisefuhrer – Portugal (eBook) (x1)',               siteCode: 'ZR',   siteName: 'ZZ R',      destination: 'Portugal' },
  { productId: '78439546', productName: 'Der Roadtrip Reisefuhrer – Lissabon Sintra Algarve -Portugal (eBook) (x1)', siteCode: 'ZR', siteName: 'ZZ R', destination: 'Portugal' },
  { productId: '78573308', productName: 'Explore and Photograph Madeira (eBook) (x1)',                    siteCode: 'ZZOE', siteName: 'ZZ EN',     destination: 'Madere' },
  { productId: '78576638', productName: 'Explorer et Photographier Madère (eBook) (x1)',                  siteCode: 'ZV',   siteName: 'ZZ FR',     destination: 'Madere' },
  { productId: '78584672', productName: 'Erkunden und Fotografieren – Madeira (eBook) (x1)',              siteCode: 'ZR',   siteName: 'ZZ R',      destination: 'Madere' },
  { productId: '78627869', productName: 'Explore and Photograph - Mallorca (eBook) (x1)',                 siteCode: 'ZZOE', siteName: 'ZZ EN',     destination: 'Majorque' },
  { productId: '78627870', productName: 'Explorer et Photographier Majorque (eBook) (x1)',                siteCode: 'ZV',   siteName: 'ZZ FR',     destination: 'Majorque' },
  { productId: '78630417', productName: 'Erkunden und Fotografieren – Mallorca (eBook) (x1)',             siteCode: 'ZR',   siteName: 'ZZ R',      destination: 'Majorque' },
  { productId: '78824666', productName: 'Le Guia de Road trip - Normandia (eBook) (x1)',                  siteCode: 'NL - ES', siteName: 'Normandie', destination: 'Normandie' },
  { productId: '78824667', productName: 'La guida per il road trip - Normandia (eBook) (x1)',             siteCode: 'NL - IT', siteName: 'Normandie', destination: 'Normandie' },
  { productId: '78824669', productName: 'De reisgis voor road trip - Normandië (eBook) (x1)',             siteCode: 'NL - NL', siteName: 'Normandie', destination: 'Normandie' },
  { productId: '78825115', productName: 'Le guia de road trip - Córcega (eBook) (x1)',                    siteCode: 'CL - IT', siteName: 'Corse',  destination: 'Corse' },
  { productId: '78826052', productName: 'La guida per il road trip - Corsica (eBook) (x1)',               siteCode: 'CL - ES', siteName: 'Corse',  destination: 'Corse' },
  { productId: '78838876', productName: 'Explorar y Fotografiar - Santorini (eBook) (x1)',                siteCode: 'ZE',   siteName: 'ZZ ES',     destination: 'Santorin' },
  { productId: '78838878', productName: 'Explorar y Fotografiar - Lanzarote (eBook) (x1)',                siteCode: 'ZE',   siteName: 'ZZ ES',     destination: 'Lanzarote' },
  { productId: '78838879', productName: 'Explorar y Fotografiar - Madeira (eBook) (x1)',                  siteCode: 'ZE',   siteName: 'ZZ ES',     destination: 'Madere' },
  { productId: '78838880', productName: 'Explorar y Fotografiar - Mallorca (eBook) (x1)',                 siteCode: 'ZE',   siteName: 'ZZ ES',     destination: 'Majorque' },
  { productId: '78838881', productName: 'Le guia de road trip - Creta (eBook) (x1)',                      siteCode: 'ZE',   siteName: 'ZZ ES',     destination: 'Crete' },
  { productId: '78838882', productName: 'La guia de road trip - Eslovenia (eBook) (x1)',                  siteCode: 'ZE',   siteName: 'ZZ ES',     destination: 'Slovenie' },
  { productId: '78840697', productName: 'De reisgis voor road trip - Corsica (eBook) (x1)',               siteCode: 'CL - NL', siteName: 'Corse',  destination: 'Corse' },
  { productId: '',         productName: 'La guia de road trip - Islandia (eBook) (x1)',                   siteCode: 'ZE',   siteName: 'ZZ ES',     destination: 'Islande' },
];
